version: '3'

services:
  # Backend service
  api:
    image: 'ecosia-gvko-api:local-dev'
    ports:
      - '3000:3000'
    expose:
      - 3030
    tty: true
    volumes:
      - './app:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - HOSTNAME=localhost
    container_name: ecosia-gvko-api